os:
  - linux
sudo: false
dist: trusty

env:
  matrix:
    - EVENT_BUILD_METHOD=autotools EVENT_CONFIGURE_OPTIONS=""

language: c
compiler:
  - gcc

before_install:
  - export JOBS=20
  - export TIMEOUT=50

branches:
  only:
    - coverity

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "ZMoNQ0SO+2+2+YdgMJ7khj1LoJtXiyncwyTiGuKt+ybifSpDPsJ3JO0UfrlwsbYnZzETFKGIW15VsHO4TIsCUV29PXo/1N5gYSwiTH5H/csnxWkOU5IeoZELkWFut7uxK3G9irHFuJFOQm9GTIerSZ1aodqP/RxBUqaopqEt/iU="

addons:
  apt:
    sources:
    - xenial
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu xenial main'
    packages:
    - zlib1g-dev
    - libssl-dev
    - build-essential
    - automake
    - autoconf
    - lcov
  coverity_scan:
    project:
      name: "libevent"
      description: "Coverity scan of libevent"
    notification_email: a3at.mail@gmail.com
    build_command_prepend: ./autogen.sh && ./configure
    build_command: make
    branch_pattern: coverity

script:
  - if [ "$EVENT_BUILD_METHOD" = "autotools" ]; then
      ./autogen.sh &&
      ./configure $EVENT_CONFIGURE_OPTIONS &&
      make &&
      travis_retry travis_wait $TIMEOUT make -j $JOBS verify;
    fi
